### ISSUE TITLE
Inference without training LLaMA with adapters

### ISSUE THREAD

**Issue by SGoel-FEra** [Srijith-rkr/WHISPERing-LLaMA#13]
Hi Srijith, Thanks for your work!

Do we need to train the model ourselves to obtain the adapter checkpoints for inference, or are they yet to be released?

**Comment by Srijith-rkr** [comment]
Hi,

Thanks for reaching out.

I didn’t upload the adapter checkpoints as I’ve since completed my internship and no longer have access to them. You’ll need to train the model yourself to generate the checkpoints for inference.

If you have any questions about the pipeline, feel free to ask, and I’ll do my best to point you in the right direction.
