### ISSUE TITLE
loss nan

### ISSUE THREAD

**Issue by fzhml** [Srijith-rkr/WHISPERing-LLaMA#6]
Do you encounter situations of nan loss during training?
![image](https://github.com/Srijith-rkr/Whispering-LLaMA/assets/68112764/287e302a-621d-4683-b879-a870e3f44c55)

**Comment by Srijith-rkr** [comment]
Hey, 

I checked my wandb logs, and the final WL method does not have nan loss values. I don't think there would be a problem unless you are consistently getting nan values. You can verify if things work out well with the WER values you get during inference and let me know. 

I had this issue (consistent nan values) when I was designing the algorithm, but I rectified it by adding layer norms and changing the initialization mechanisms of the adapter modules.

**Comment by fzhml** [comment]
Thank you for your response. Additionally, I noticed that there are some duplicates of ground truth in the Gigaspeech data. I'm not sure if this could cause information leakage.

**Comment by Srijith-rkr** [comment]
No problem. 

I am not sure what you mean by duplicates of ground truth. Do you mean some data points are repeated in the train and test sets?

**Comment by fzhml** [comment]
What I mean is that some identical labels appear in many samples.below is a top-20 of giga-ScienceAndTechnology, first column represents the occurrences.
![image](https://github.com/Srijith-rkr/Whispering-LLaMA/assets/68112764/a9da91d9-1d21-456e-8737-adc3bff7e314)

**Comment by Srijith-rkr** [comment]
I did not check this during my experiments. Understandably, words like "yeah" and "okay" are repeated, but are the audio clips also the same for the longer sentences? If yes, they are duplicates in the dataset and could cause problems, as you mentioned. 

We would not have the same problem with the ATIS dataset in the paper since it is clean compared to Gigaspeech. (Gigaspeech is created from YouTube videos, podcasts and audiobooks.)

**Comment by fzhml** [comment]
Thanks for your reply. Unfortunately, I listened to several long audio segments, and it seems they are the same. i'll filter dataset or switch to ATIS dataset。But I still have a question: the script filters out the correct answers during training, but it seems it cannot do the same during inference. Is this also an issue?

**Comment by Srijith-rkr** [comment]
I used the same script to generate the training and test sets. Therefore, the test prompts also do not have the ground truth as part of the n-best hypotheses in the prompt during inference. I did this to check if the model is able to generate the correct hypothesis rather than just pick the best one.

It would not be an issue if the correct hypothesis is also present in the model prompt.

Let me know if you have any other questions.
